tokens:
      - chainName: kasplextestnet
        standard: EvmHypSynthetic
        decimals: 18
        symbol: USDT
        name: Tether USD
        addressOrDenom: "0x5510d3F4D1D5C8c8CB564f786324ec9026C32087"
        connections:
          - token: ethereum|bsctestnet|0x56F7805EeAD72A2a8a3D5D5aca6Ed4677C1abccc
      - chainName: bsctestnet
        standard: EvmHypCollateral
        decimals: 18
        symbol: USDT
        name: Tether USD
        addressOrDenom: "0x56F7805EeAD72A2a8a3D5D5aca6Ed4677C1abccc"
        collateralAddressOrDenom: "0xb97aDD318e75F98972f95323ce0A035E31784c4E"
        connections:
          - token: ethereum|kasplextestnet|0x5510d3F4D1D5C8c8CB564f786324ec9026C32087
        