 tokens:
      - chainName: kasplextestnet
        standard: EvmHypSynthetic
        decimals: 18
        symbol: USDT
        name: Tether USD
        addressOrDenom: "0x0EDB941Af94c4AeEBfEf368e633a0aaF1161d372"
        connections:
          - token: ethereum|bsctestnet|0x1a093bC0c8E9eE558e8251835Ee9E1DCd51aab24
      - chainName: bsctestnet
        standard: EvmHypCollateral
        decimals: 18
        symbol: USDT
        name: Tether USD
        addressOrDenom: "0x1a093bC0c8E9eE558e8251835Ee9E1DCd51aab24"
        collateralAddressOrDenom: "0xb97aDD318e75F98972f95323ce0A035E31784c4E"
        connections:
          - token: ethereum|kasplextestnet|0x0EDB941Af94c4AeEBfEf368e633a0aaF1161d372