# yaml-language-server: $schema=../schema.json
tokens:
  - chainName: kasplextestnet
    standard: EvmHypCollateral
    addressOrDenom: "0xEf36d07698b773676f730fdcE1214B67c87406EA"
    collateralAddressOrDenom: "0x370C50b7F79D30ED9D7cC67C318F870035924beF"
    decimals: 18
    symbol: USDT
    name: Tether USD

  - chainName: bsctestnet
    standard: EvmHypCollateral
    addressOrDenom: "0xb97aDD318e75F98972f95323ce0A035E31784c4E"
    decimals: 18
    symbol: USDT
    name: Tether USD

